FROM openjdk:21-jdk-slim
WORKDIR /app
COPY target/acebook-template-1.0-SNAPSHOT.jar /app/jacebook.jar
EXPOSE 8080

ENV JDBC_CONNECTION=$JDBC_CONNECTION
ENV JDBC_USER_NAME=$JDBC_USER_NAME
ENV JDBC_PASSWORD=$JDBC_PASSWORD
ENV OKTA_ISSUER_URL=$OKTA_ISSUER_URL
ENV OKTA_CLIENT_ID=$OKTA_CLIENT_ID
ENV OKTA_CLIENT_SECRET=$OKTA_CLIENT_SECRET
ENV E2_PUBLIC_ENDPOINT=$E2_PUBLIC_ENDPOINT
ENV E2_ENDPOINT=$E2_ENDPOINT
ENV E2_BUCKET_NAME=$E2_BUCKET_NAME
ENV E2_ACCESS_KEY=$E2_ACCESS_KEY
ENV E2_SECRET_KEY=$E2_SECRET_KEY

# Run the JAR file
ENTRYPOINT ["java", "-jar", "/app/jacebook.jar"]
